### ISSUE TITLE
Cosmetic problem 

### ISSUE THREAD

**Issue by JPGuillemin** [4v3ngR/ytm-wrapped#10]
There's a whiteblue square around the Artist name each time you open an Artist channel.

**Comment by JPGuillemin** [comment]
![Uploading Screenshot_20220411-090445_ytm-wrapped.jpg…]()

**Comment by JPGuillemin** [comment]
![Screenshot_20220411-090445_ytm-wrapped](https://user-images.githubusercontent.com/55490396/162722187-1d7081ad-10f0-424d-831f-861ce8c202c6.jpg)

**Comment by 4v3ngR** [comment]
yeah, that's an issue with android's accessibility support. I'll investigate to see if it can be turned off

**Comment by 4v3ngR** [comment]
changed the css rule to remove the outline on all nodes. This should fix the issue.
