### ISSUE TITLE
Icon proposal

### ISSUE THREAD

**Issue by JPGuillemin** [4v3ngR/ytm-wrapped#11]
Hi, 

Attached a new icon, that I made for you.
![YTMW](https://user-images.githubusercontent.com/55490396/162736125-2284b5b1-1d97-44da-a3f7-1115fdaa1fde.svg)

**Comment by 4v3ngR** [comment]
nice. Thanks for that.

**Comment by 4v3ngR** [comment]
The icon has been added and will be in the next build
