### ISSUE TITLE
Sound cuts when starting another app 

### ISSUE THREAD

**Issue by JPGuillemin** [4v3ngR/ytm-wrapped#12]
Whenever an app is launched during playback there's a short cut in audio playing.
You should search for a way to get realtime scheduling privilege so that YtmW has priority as a sound app : and therefore sound is not cut.

All music players I have tested on Android have this processing priority, so there should be a way to do it.

All the best

**Comment by 4v3ngR** [comment]
Can you provide details about your phone? I've been using this on an old android 8 tablet and I have no issues. On my phone (Vivo y20s) I had to enabled unrestricted data as well as unrestricted background power usage.

I also did some research and android does not have a concept of realtime scheduling. If you have any information contrary to this (with code examples) it would be helpful.

**Comment by JPGuillemin** [comment]
I'm using a Samsung A52s.

Android is a Linux system, so under the hood there's a scheduling policy. Some apps are priority processes, and some are not.
I'm not an Android dev either:)

**Comment by JPGuillemin** [comment]
What I would do : compare Android privileges given to a well known music app, for exemple Spotify, to see if some privileges are missing to YTMW.

Spotify can play the stream in the background without unrestricted battery usage. 

Unrestricted battery for an app should be avoided : it's a dirty workaround that kill smartphone autonomy.

**Comment by JPGuillemin** [comment]
Maybe this is related to buffering, ...

**Comment by 4v3ngR** [comment]
cannot fix in the app.

**Comment by JPGuillemin** [comment]
https://www.tutorialspoint.com/how-to-use-set-the-priority-for-a-thread-in-android

**Comment by JPGuillemin** [comment]
https://www.tutorialspoint.com/how-to-set-web-view-render-priority-in-android

**Comment by JPGuillemin** [comment]
Sure there's a way to fix it in the app 

Please reopen :)
