### ISSUE TITLE
app stops and music stop playing after 5-10 minutes in background.

### ISSUE THREAD

**Issue by gsingh704** [4v3ngR/ytm-wrapped#13]
Latest version plus many before it
on Android 12 and 11 on Realme/Oppo

**Comment by 4v3ngR** [comment]
check that the app has unrestricted network and battery permission. It isn't the app that stops, it is android that is stopping the app.

**Comment by gsingh704** [comment]
Tried many  things like disabling optimization etc  to no avail

**Comment by gsingh704** [comment]
I don't really have any idea but maybe this can help
https://github.com/katzer/cordova-plugin-background-mode
