### ISSUE TITLE
Media laggy when in background on lineage os(many versions tested)

### ISSUE THREAD

**Issue by gsingh704** [4v3ngR/ytm-wrapped#14]

**Comment by 4v3ngR** [comment]
The app is bound by the performance of the following:
* capacitor
* the cordova in app browser
* youtube music web site
* the communication between the three

There's not much this app can do to improve the performance of the app when in the background. I'll note that I have no issues with background playback on a crappy android tablet running android 8 with 1GB or memory.

If you could, try building the app and see if you can find anywhere that can be improved (performance wise)
