### ISSUE TITLE
App crash or stutter in background on custom rom without GAPPS included , if you flash GAPPS after , then also it sttuters. ONly works with roms that have come GAPPS

### ISSUE THREAD

**Issue by gsingh704** [4v3ngR/ytm-wrapped#15]

**Comment by 4v3ngR** [comment]
I've this working without issues on a huawei tablet that has no google stuff at all. Perhaps it is an issue with your custom firmware - specifically the webview component that is provided. There's nothing that can be done in the app to work around issues in the firmware. I suggest raising a bug with the firmware providers to say to them their webview component does not work correctly.
