### ISSUE TITLE
When using extended menu to get volume, shuffle controls etc. There should be like and dislike button but they dont appear in portrait mode. Also to unhide that menu the arrow is hidden and can't be touched. So one time opened that menu you can't unhide it till next session.

### ISSUE THREAD

**Issue by gsingh704** [4v3ngR/ytm-wrapped#6]

**Comment by gsingh704** [comment]
![Screenshot_2022-04-03-12-58-26-76_7dd92e09d44bf4c6d93e1d850b756914](https://user-images.githubusercontent.com/85999340/161424406-824c0dd5-f135-4c61-9653-699aaae1da91.jpg)

**Comment by gsingh704** [comment]
Suggestions: hide volune control behid volume logo(only appear when clucked on icon). Not sure if it's possible. But in my case I dont really need it.

**Comment by 4v3ngR** [comment]
I'll see what I can do. I would actually like to "redesign" the entire player UI to be a bit more spaced out. I've already got code to hide and show the "Up Next", "Lyrics", and "Related" section. What I'll do is move those extra buttons (and the volume) into the space.

**Comment by 4v3ngR** [comment]
The 0.1.9 release moves the extra controls into the player page. I'll likely do more work in the future to find better placement, but for now, this is done.
