### ISSUE TITLE
Playback stop after a few seconds in background 

### ISSUE THREAD

**Issue by JPGuillemin** [4v3ngR/ytm-wrapped#8]
Playback stop after a few seconds in background

**Comment by 4v3ngR** [comment]
Are you able to test with previous releases and determine if it was always an issue?

**Comment by JPGuillemin** [comment]
It seems fixed with latest update 022.

Still some buffering issues stoping pkayback when network connection is unreliable.

**Comment by JPGuillemin** [comment]
Fixed with 0.2.2
