### ISSUE TITLE
Realtime execution issue

### ISSUE THREAD

**Issue by JPGuillemin** [4v3ngR/ytm-wrapped#9]
When app is in background and another app is launched (ie : browser) a sound microcut happens most of the time.

App should run with higher realtime priority.

**Comment by JPGuillemin** [comment]
Doze disabled :)

**Comment by phartshorn** [comment]
I've been able to run this on an $80 tablet running android 8 with no issues. What hardware are you using that is having problems?

**Comment by 4v3ngR** [comment]
wake lock and foreground service was added back. If it still pauses when you lock your phone, I recommend grabbing the code and raise an MR

**Comment by JPGuillemin** [comment]
Problem wasn't at lock time. It was realtime prio problem versus other apps.

It seems better with 0.2.3. 
Great job
